name: github-action-runner-tests
on: push
jobs:
  Ubuntu-ARM64:
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: ubuntu-latest-arm64
        run: echo "ubuntu-latest arm64"
      - name: lsb_release -a
        run: lsb_release -a
      - name: lscpu
        run: lscpu

  Windows-ARM64:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x64'
            plat: 'x64'
            win_ver: 'Win64'
          - arch: 'x86'
            plat: 'Win32'
            win_ver: 'Win32'
          - arch: 'arm64'
            plat: 'ARM64'
            win_ver: 'WinARM64'    
    steps:
      - name: windows-latest-arm64
        run: echo "windows-latest arm64"
      - name: systeminfo
        run: systeminfo

  MacOS-ARM64:
    runs-on: [macos-latest]
    steps:
      - name: macos-latest
        run: echo "macos-latest"
      - name: sw_vers
        run: sw_vers
      - name: sysctl -a | grep brand
        run: sysctl -a | grep brand
      - name: sysctl -n hw.ncpu
        run: sysctl -n hw.ncpu
