name: github-action-runner-tests
on: push
jobs:
  Ubuntu-ARM64:
    runs-on: [ubuntu-latest, ARM64]
    steps:
      - name: ubuntu-latest-arm64
        run: echo "ubuntu-latest arm64"
      - name: lsb_release -a
        run: lsb_release -a
      - name: lscpu
        run: lscpu

  Windows-ARM64:
    runs-on: [windows-latest, ARM64]
    steps:
      - name: windows-latest-arm64
        run: echo "windows-latest arm64"
      - name: ver
        run: ver
      - name: wmic cpu get name
        run: wmic cpu get name

  MacOS-ARM64:
    runs-on: [macos-latest]
    steps:
      - name: macos-latest
        run: echo "macos-latest"
      - name: sw_vers
        run: sw_vers
      - name: sysctl -a | grep brand
        run: sysctl -a | grep brand
      - name: sysctl -n hw.ncpu
        run: sysctl -n hw.ncpu
